// import 'package:flutter/material.dart';

// class Product {
//   final String image, title, description, price;
//   final int id;
//   final Color color;
//   final double rating;

//   Product({
//     this.id,
//     this.image,
//     this.title,
//     this.description,
//     this.price,
//     this.color,
//     this.rating,
//   });
// }

// List<Product> product = [
//   Product(
//     id: 1,
//     title: "Strawberry",
//     description: "01 KG",
//     price: "\$50",
//     image: "assets/images/Product/strawberry.png",
//     color: Color(0xFFFFEFF2),
//     rating: 4.5,
//   ),
//   Product(
//     id: 2,
//     title: "Grapes",
//     description: "01 KG",
//     price: "\$40",
//     image: "assets/images/Product/grapes.png",
//     color: Color(0xFFF3EBFF),
//     rating: 4.5,
//   ),
//   Product(
//     id: 3,
//     title: "Banana",
//     description: "01 Dozen",
//     price: "\$35",
//     image: "assets/images/Product/bananas.png",
//     color: Color(0xFFFFFBE6),
//     rating: 4.5,
//   ),
//   Product(
//     id: 4,
//     title: "Strawberry",
//     description: "01 KG",
//     price: "\$50",
//     image: "assets/images/Product/strawberry.png",
//     color: Color(0xFFFFEFF2),
//     rating: 4.5,
//   ),
//   Product(
//     id: 5,
//     title: "Grapes",
//     description: "01 KG",
//     price: "\$40",
//     image: "assets/images/Product/grapes.png",
//     color: Color(0xFFF3EBFF),
//     rating: 4.5,
//   ),
//   Product(
//     id: 6,
//     title: "Banana",
//     description: "01 Dozen",
//     price: "\$35",
//     image: "assets/images/Product/bananas.png",
//     color: Color(0xFFFFFBE6),
//     rating: 4.5,
//   ),
//   Product(
//     id: 7,
//     title: "Strawberry",
//     description: "01 KG",
//     price: "\$50",
//     image: "assets/images/Product/strawberry.png",
//     color: Color(0xFFFFEFF2),
//     rating: 4.5,
//   ),
//   Product(
//     id: 8,
//     title: "Grapes",
//     description: "01 KG",
//     price: "\$40",
//     image: "assets/images/Product/grapes.png",
//     color: Color(0xFFF3EBFF),
//     rating: 4.5,
//   ),
//   Product(
//     id: 9,
//     title: "Banana",
//     description: "01 Dozen",
//     price: "\$35",
//     image: "assets/images/Product/bananas.png",
//     color: Color(0xFFFFFBE6),
//     rating: 4.5,
//   ),
//   Product(
//     id: 10,
//     title: "Strawberry",
//     description: "01 KG",
//     price: "\$50",
//     image: "assets/images/Product/strawberry.png",
//     color: Color(0xFFFFEFF2),
//     rating: 4.5,
//   ),
//   Product(
//     id: 11,
//     title: "Grapes",
//     description: "01 KG",
//     price: "\$40",
//     image: "assets/images/Product/grapes.png",
//     color: Color(0xFFF3EBFF),
//     rating: 4.5,
//   ),
//   Product(
//     id: 12,
//     title: "Banana",
//     description: "01 Dozen",
//     price: "\$35",
//     image: "assets/images/Product/bananas.png",
//     color: Color(0xFFFFFBE6),
//     rating: 4.5,
//   ),
//   Product(
//     id: 13,
//     title: "Strawberry",
//     description: "01 KG",
//     price: "\$50",
//     image: "assets/images/Product/strawberry.png",
//     color: Color(0xFFFFEFF2),
//     rating: 4.5,
//   ),
//   Product(
//     id: 14,
//     title: "Grapes",
//     description: "01 KG",
//     price: "\$40",
//     image: "assets/images/Product/grapes.png",
//     color: Color(0xFFF3EBFF),
//     rating: 4.5,
//   ),
//   Product(
//     id: 15,
//     title: "Banana",
//     description: "01 Dozen",
//     price: "\$35",
//     image: "assets/images/Product/bananas.png",
//     color: Color(0xFFFFFBE6),
//     rating: 4.5,
//   ),
//   Product(
//     id: 16,
//     title: "Strawberry",
//     description: "01 KG",
//     price: "\$50",
//     image: "assets/images/Product/strawberry.png",
//     color: Color(0xFFFFEFF2),
//     rating: 4.5,
//   ),
//   Product(
//     id: 17,
//     title: "Grapes",
//     description: "01 KG",
//     price: "\$40",
//     image: "assets/images/Product/grapes.png",
//     color: Color(0xFFF3EBFF),
//     rating: 4.5,
//   ),
//   Product(
//     id: 18,
//     title: "Banana",
//     description: "01 Dozen",
//     price: "\$35",
//     image: "assets/images/Product/bananas.png",
//     color: Color(0xFFFFFBE6),
//     rating: 4.5,
//   ),
// ];
